"""Registered audit literals for provider/facility trust-state transitions.

No transition endpoint is introduced in this slice.  Future authority-changing
work must use durable audit/outbox handling before committing these events.
"""

from enum import Enum


class ProviderTrustAuditEvent(str, Enum):
    PROVIDER_ACCOUNT_BOOTSTRAPPED = "PROVIDER_ACCOUNT_BOOTSTRAPPED"
    PROVIDER_PROFESSIONAL_VERIFICATION_SUBMITTED = (
        "PROVIDER_PROFESSIONAL_VERIFICATION_SUBMITTED"
    )
    PROVIDER_PROFESSIONAL_VERIFIED = "PROVIDER_PROFESSIONAL_VERIFIED"
    PROVIDER_PROFESSIONAL_REJECTED = "PROVIDER_PROFESSIONAL_REJECTED"
    PROVIDER_PROFESSIONAL_SUSPENDED = "PROVIDER_PROFESSIONAL_SUSPENDED"
    PROVIDER_PROFESSIONAL_RESTORED = "PROVIDER_PROFESSIONAL_RESTORED"
    PROVIDER_REVERIFICATION_PERFORMED = "PROVIDER_REVERIFICATION_PERFORMED"
    PROVIDER_VERIFICATION_SOURCE_UNAVAILABLE = (
        "PROVIDER_VERIFICATION_SOURCE_UNAVAILABLE"
    )
    FACILITY_VERIFICATION_SUBMITTED = "FACILITY_VERIFICATION_SUBMITTED"
    FACILITY_VERIFIED = "FACILITY_VERIFIED"
    FACILITY_REJECTED = "FACILITY_REJECTED"
    FACILITY_SUSPENDED = "FACILITY_SUSPENDED"
    FACILITY_RESTORED = "FACILITY_RESTORED"
    AFFILIATION_ACTIVATED = "AFFILIATION_ACTIVATED"
    AFFILIATION_SUSPENDED = "AFFILIATION_SUSPENDED"
    AFFILIATION_REVOKED = "AFFILIATION_REVOKED"
    AFFILIATION_RESTORED = "AFFILIATION_RESTORED"
    CLINICAL_ELIGIBILITY_DENIED = "CLINICAL_ELIGIBILITY_DENIED"
    DELEGATED_CLINICAL_TRUST_DENIED = "DELEGATED_CLINICAL_TRUST_DENIED"
